security:
  oauth2:
    client:
      clientId: your-midentity-box-oidc-app-client-id
      clientSecret: your-midentity-box-oidc-app-client-secret
      accessTokenUri: https://{partnerid}.{hostname}/digitanium/v1/login
      userAuthorizationUri: https://{partnerid}.{hostname}/digitanium/v1/auth
      authorizedGrantTypes: authorization_code
      scope: openid,profile,email
    resource:
      userInfoUri: https://{partnerid}.{hostname}/digitanium/v1/userinfo

server:
  port : 8082
